name: Playwright Tests

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx --yes envinfo --preset playwright
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test
